# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Tools.
# ------------------------------------------------------

TEMPLATE = app
TARGET = WarframeFissureUtil
DESTDIR = ../x64/Debug
CONFIG += debug
DEFINES += $(Qt_DEFINES_) QGOODWINDOW
LIBS += -L"." \
    -l/"$(INHERIT)/" \
    -l$(Qt_LIBS_)
DEPENDPATH += .
MOC_DIR += .
OBJECTS_DIR += debug
UI_DIR += .
RCC_DIR += .
